language: cpp

os:
  - linux
  - osx

compiler:
  - clang

script:
  - make -C cimgui

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE cimgui/cimgui.dylib"
  skip_cleanup: true
  on:
    tags: true
